/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2008
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  pal_sap.h
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  PAL SAP
 *
 * Author:
 * -------
 *  Saker Hsia (mtk02327)
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Log$
 *
 * 10 27 2010 sh.lai
 * [ALPS00022255] [Need Patch] [Volunteer Patch] Porting PAL interface for BT task
 * New feature ALPS00022255 : [Need Patch] [Volunteer Patch] Porting PAL interface for BT task.
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/

/****************************************************************************
 *  Messages: WNDRV -> PAL
 ****************************************************************************/
MSG_ID_PAL_WNDRV_MAC_START_IND = MSG_ID_PAL_MSG_CODE_BEGIN,
MSG_ID_PAL_WNDRV_MAC_CONNECT_IND,
MSG_ID_PAL_WNDRV_MAC_CONNECT_FAIL_IND,
MSG_ID_PAL_WNDRV_MAC_DISCONNECT_IND,
MSG_ID_PAL_WNDRV_MAC_CANCEL_IND,
MSG_ID_PAL_WNDRV_QUERY_STATUS_IND,
MSG_ID_PAL_WNDRV_SYNC_TSF_IND,
// For Data Link Manager
MSG_ID_PAL_WNDRV_DATA_IND,
MSG_ID_PAL_WNDRV_DATA_BLOCK_FREE_NUM_IND,

/****************************************************************************
 *  Messages: BT -> PAL
 ****************************************************************************/
// For PAL Manager
MSG_TAG_PAL_BT_SEND_START,
MSG_TAG_PAL_BT_FIRST_REQ_MSG = MSG_TAG_PAL_BT_SEND_START,
MSG_ID_PAL_BT_READ_LOCAL_VERSION_INFO_COMMAND = MSG_TAG_PAL_BT_FIRST_REQ_MSG,
MSG_ID_PAL_BT_READ_LOCAL_AMP_INFO_COMMAND,
MSG_ID_PAL_BT_READ_LOCAL_AMP_ASSOC_COMMAND,
MSG_ID_PAL_BT_RESET_COMMAND,
MSG_ID_PAL_BT_READ_DATA_BLOCK_SIZE_COMMAND,
// For Physical Link Manager
MSG_ID_PAL_BT_READ_LINK_QUALITY_COMMAND,
MSG_ID_PAL_BT_READ_RSSI_COMMAND,
MSG_ID_PAL_BT_WRITE_REMOTE_AMP_ASSOC_COMMAND,
MSG_ID_PAL_BT_CREATE_PHYSICAL_LINK_COMMAND,
MSG_ID_PAL_BT_ACCEPT_PHYSICAL_LINK_COMMAND,
MSG_ID_PAL_BT_READ_LINK_SUPERVISON_TIMEOUT_COMMAND,
MSG_ID_PAL_BT_DISCONNECT_PHYSICAL_LINK_COMMAND,
MSG_ID_PAL_BT_WRITE_LINK_SUPERVISON_TIMEOUT_COMMAND,
// For Logical Link Manager
MSG_ID_PAL_BT_CREATE_LOGICAL_LINK_COMMAND,
MSG_ID_PAL_BT_ACCEPT_LOGICAL_LINK_COMMAND,
MSG_ID_PAL_BT_FLOW_SPEC_MODIFY_COMMAND,
MSG_ID_PAL_BT_DISCONNECT_LOGICAL_LINK_COMMAND,
MSG_ID_PAL_BT_LOGICAL_LINK_CANCEL_COMMAND,
MSG_ID_PAL_BT_READ_LOGICAL_LINK_ACCEPT_TIMEOUT_COMMAND,
MSG_ID_PAL_BT_WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT_COMMAND,
// For Data Link Manager 
MSG_ID_PAL_BT_ENHANCED_FLUSH_COMMAND,
MSG_ID_PAL_BT_SHORT_RANGE_MODE_COMMAND,
MSG_ID_PAL_BT_DATA_COMMAND,
MSG_TAG_PAL_BT_SEND_END = MSG_ID_PAL_BT_DATA_COMMAND,

/****************************************************************************
 *  Messages: PAL -> WNDRV
 ****************************************************************************/
MSG_ID_PAL_WNDRV_MAC_START_REQ,
MSG_ID_PAL_WNDRV_MAC_CONNECT_REQ,
MSG_ID_PAL_WNDRV_ADD_KEY_REQ,
MSG_ID_PAL_WNDRV_MAC_DISCONNECT_REQ,
MSG_ID_PAL_WNDRV_MAC_CANCEL_REQ,
MSG_ID_PAL_WNDRV_DATA_REQ,
MSG_ID_PAL_WNDRV_QUERY_STATUS_REQ,
MSG_ID_PAL_WNDRV_SET_ACTIVITY_REPORT_REQ,
MSG_ID_PAL_WNDRV_SHORT_RANGE_MODE_REQ,
/***************** The above SAP definitions should not be moved !!!! ****************/

/****************************************************************************
 *  Messages: PAL -> BT
 ****************************************************************************/
MSG_TAG_PAL_BT_RECV_START,
MSG_ID_PAL_BT_READ_LOCAL_VERSION_COMPLETE_EVENT = MSG_TAG_PAL_BT_RECV_START,
MSG_ID_PAL_BT_READ_LOCAL_AMP_INFO_COMPLETE_EVENT,
MSG_ID_PAL_BT_READ_LOCAL_AMP_ASSOC_COMPLETE_EVENT,
MSG_ID_PAL_BT_CHNAGE_AMP_STATUS_EVENT,
MSG_ID_PAL_BT_RESET_COMPLETE_EVENT,
MSG_ID_PAL_BT_READ_DATA_BLOCK_SIZE_COMPLETE_EVENT,
// For Physical Link Manager
MSG_ID_PAL_BT_CHANNEL_SELECTED_EVENT,
MSG_ID_PAL_BT_READ_LINK_QUALITY_COMPLETE_EVENT,
MSG_ID_PAL_BT_READ_RSSI_COMPLETE_EVENT,
MSG_ID_PAL_BT_WRITE_REMOTE_AMP_ASSOC_COMPLETE_EVENT,
MSG_ID_PAL_BT_CREATE_PHYSICAL_LINK_STATUS_EVENT,
MSG_ID_PAL_BT_ACCEPT_PHYSICAL_LINK_STATUS_EVENT,
MSG_ID_PAL_BT_PHYSICAL_LINK_COMPLETE_EVENT,
MSG_ID_PAL_BT_READ_LINK_SUPERVISON_TIMEOUT_COMPLETE_EVENT,
MSG_ID_PAL_BT_DISCONNECT_PHYSICAL_LINK_STATUS_EVENT,
MSG_ID_PAL_BT_DISCONNECT_PHYSICAL_LINK_COMPLETE_EVENT,
MSG_ID_PAL_BT_PHYSICAL_LINK_LOSS_EARLY_WARNING_EVENT,
MSG_ID_PAL_BT_WRITE_LINK_SUPERVISON_TIMEOUT_COMPLETE_EVENT,
// For Logical Link Manager
MSG_ID_PAL_BT_CREATE_LOGICAL_LINK_STATUS_EVENT,
MSG_ID_PAL_BT_ACCEPT_LOGICAL_LINK_STATUS_EVENT,
MSG_ID_PAL_BT_FLOW_SPEC_MODIFY_STATUS_EVENT,
MSG_ID_PAL_BT_FLOW_SPEC_MODIFY_COMPLETE_EVENT,
MSG_ID_PAL_BT_LOGICAL_LINK_COMPLETE_EVENT,
MSG_ID_PAL_BT_DISCONNECT_LOGICAL_LINK_STATUS_EVENT,
MSG_ID_PAL_BT_DISCONNECT_LOGICAL_LINK_COMPLETE_EVENT,
MSG_ID_PAL_BT_LOGICAL_LINK_CANCEL_STATUS_EVENT,
MSG_ID_PAL_BT_LOGICAL_LINK_CANCEL_COMPLETE_EVENT,
MSG_ID_PAL_BT_READ_LOGICAL_LINK_ACCEPT_TIMEOUT_COMPLETE_EVENT,
MSG_ID_PAL_BT_WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT_COMPLETE_EVENT,
// For Data Link Manager
MSG_ID_PAL_BT_NUM_OF_COMPLETE_DATA_BLOCKS_EVENT,
MSG_ID_PAL_BT_ENHANCED_FLUSH_STATUS_EVENT,
MSG_ID_PAL_BT_ENHANCED_FLUSH_COMPLETE_EVENT,
MSG_ID_PAL_BT_SHORT_RANGE_MODE_STATUS_EVENT,
MSG_ID_PAL_BT_SHORT_RANGE_MODE_CHNAGE_COMPLETE_EVENT,
MSG_ID_PAL_BT_DATA_EVENT,
MSG_TAG_PAL_BT_LAST_REQ_MSG = MSG_ID_PAL_BT_DATA_EVENT,
